### ISSUE TITLE
Entities are spawned during the preview

### ISSUE THREAD

**Issue by RedstoneFuture** [eldoriarpg/SchematicBrushReborn#193] opened 2022-12-14 14:21 UTC
If I use the activated preview (`/sbrs preview true`) entities are always spawning - also without placing.

![grafik](https://user-images.githubusercontent.com/4140635/207619680-8830afe3-1c92-4da2-9d98-a53062fffd52.png)

**How to replicate:**
- `//copy -e`
- `//schem save ...`
- bind the item with the target schematic
- activate preview `/sbrs preview true`
- without placing (right click), entities are spawning

**tested with:**
- FastAsyncWorldEdit-Bukkit-2.4.11-SNAPSHOT
- Schematic Brush Reborn 2 v. 2.2.5
- PaperMC 1.19.2 build 200
- ProtocolLib v5.0.0-SNAPSHOT-b602

**Comment by RainbowDashLabs** [comment] 2022-12-17 21:06
Thanks for the report. The issue is fixed in the next release available on Spigot and Patreon soon ^^

**Closed by RainbowDashLabs** 2022-12-17 21:06 UTC
Labels: bug
